# Generated by Django 5.1.7 on 2025-04-12 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_is_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unite',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unites_crees', to=settings.AUTH_USER_MODEL),
        ),
    ]
