# Generated by Django 5.1.7 on 2025-03-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juridiquefournisseur',
            name='etat',
            field=models.CharField(choices=[('HABILITE', 'Habilité'), ('BLACKLISTE', 'Blacklisté')], default='HABILITE', max_length=50),
        ),
        migrations.AlterModelTable(
            name='juridiquefournisseur',
            table='JURIDIQUE_FOURNISSEUR',
        ),
    ]
