-- Suppression des tables existantes
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DJANGO_MIGRATIONS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE DJANGO_CONTENT_TYPE CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE AUTH_PERMISSION CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE AUTH_GROUP CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE AUTH_GROUP_PERMISSIONS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE AUTH_USER CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE AUTH_USER_GROUPS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE AUTH_USER_USER_PERMISSIONS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE CONTRACTS_EVALUATIONCONTRAT CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE CONTRACTS_UNITE_USERS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE CONTRACTS_JURIDIQUEFOURNISSEUR CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE CONTRACTS_UNITE CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE CONTRACTS_CONTRAT CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE DJANGO_SESSION CASCADE CONSTRAINTS';
END;
/
