# Generated by Django 5.1.7 on 2025-03-17 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0003_remove_contrat_fournisseur_remove_unite_users_and_more'),
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationFournisseur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contractant', models.CharField(max_length=255)),
                ('ecoute_client', models.IntegerField()),
                ('respect_delais_contract', models.IntegerField()),
                ('respect_des_autres_obligations', models.IntegerField()),
                ('taux_conformite', models.IntegerField()),
                ('flexibilite', models.IntegerField()),
                ('total_evaluation', models.IntegerField()),
                ('remarque', models.TextField(blank=True, null=True)),
                ('id_contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contrat')),
                ('id_fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.juridiquefournisseur')),
            ],
        ),
    ]
