# Generated by Django 5.1.7 on 2025-03-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_fournisseur', models.IntegerField()),
                ('contractant', models.CharField(max_length=255)),
                ('ecoute_client', models.IntegerField()),
                ('respect_delais_contrat', models.IntegerField()),
                ('respect_des_autres_obligations', models.IntegerField()),
                ('taux_conformite', models.FloatField()),
                ('flexibilite', models.IntegerField()),
                ('total_evaluation', models.IntegerField()),
                ('remarque', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JuridiqueFournisseur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_du_contractant', models.CharField(max_length=255)),
                ('num_fixe', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nif', models.CharField(blank=True, max_length=50, null=True)),
                ('date_exclusion', models.DateField(blank=True, null=True)),
                ('duree_exclusion', models.IntegerField(blank=True, null=True)),
                ('date_levee_sanction', models.DateField(blank=True, null=True)),
                ('etat', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('structure_ayant_exclu', models.CharField(blank=True, max_length=255, null=True)),
                ('motifs', models.TextField(blank=True, null=True)),
                ('remarques', models.TextField(blank=True, null=True)),
                ('activite', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('wilaya', models.CharField(blank=True, max_length=100, null=True)),
                ('n_identification_fiscale', models.CharField(blank=True, max_length=100, null=True)),
                ('n_identification_statistique', models.CharField(blank=True, max_length=100, null=True)),
                ('n_registre_commerce', models.CharField(blank=True, max_length=100, null=True)),
                ('article_imposition', models.CharField(blank=True, max_length=100, null=True)),
                ('systeme_numerotation_universel', models.CharField(blank=True, max_length=100, null=True)),
                ('carte_artisant', models.CharField(blank=True, max_length=100, null=True)),
                ('num_agrement', models.CharField(blank=True, max_length=100, null=True)),
                ('crit_rech_1', models.CharField(blank=True, max_length=100, null=True)),
                ('rue', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone_2', models.CharField(blank=True, max_length=20, null=True)),
                ('forme_juridique', models.CharField(blank=True, max_length=100, null=True)),
                ('branche', models.CharField(blank=True, max_length=100, null=True)),
                ('type_partenaire', models.CharField(blank=True, max_length=100, null=True)),
                ('cle_pays_banque', models.CharField(blank=True, max_length=10, null=True)),
                ('cle_bancaire', models.CharField(blank=True, max_length=10, null=True)),
                ('compte_bancaire', models.CharField(blank=True, max_length=50, null=True)),
                ('cle_controle_bancaire', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id_site', models.AutoField(primary_key=True, serialize=False)),
                ('nom_site', models.CharField(max_length=255)),
            ],
        ),
    ]
