# Generated by Django 5.1.7 on 2025-04-18 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20250412_0240'),
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dossier_consultation', models.FileField(blank=True, null=True, upload_to='contrats/dossiers/')),
                ('pv_ouverture', models.FileField(blank=True, null=True, upload_to='contrats/pv_ouverture/')),
                ('pv_attribution_prov_marche', models.FileField(blank=True, null=True, upload_to='contrats/pv_attribution/')),
                ('copie_du_contrat', models.FileField(blank=True, null=True, upload_to='contrats/copies/')),
                ('lettre_de_prolongation', models.FileField(blank=True, null=True, upload_to='contrats/prolongations/')),
                ('lettre_invitation', models.FileField(blank=True, null=True, upload_to='contrats/lettres_invitation/')),
                ('date_prev_attrib_contrat', models.DateField(blank=True, null=True)),
                ('date_prev_signat_contrat_bon', models.DateField(blank=True, null=True)),
                ('date_reel_signat_contr_bon', models.DateField(blank=True, null=True)),
                ('date_prev_notif_attribu', models.DateField(blank=True, null=True)),
                ('date_reel_notif_attrib', models.DateField(blank=True, null=True)),
                ('date_prev_signature_contrat', models.DateField(blank=True, null=True)),
                ('date_reel_sign_cont', models.DateField(blank=True, null=True)),
                ('date_exp_du_contrat', models.DateField(blank=True, null=True)),
                ('date_saisie_contract', models.DateField(auto_now_add=True)),
                ('date_install_equip', models.DateField(blank=True, null=True)),
                ('delais_estimatif_execut_livrai', models.CharField(blank=True, max_length=100, null=True)),
                ('delais_execution_livraison', models.CharField(blank=True, max_length=100, null=True)),
                ('duree_contrat', models.CharField(blank=True, max_length=100, null=True)),
                ('duree_attrib_contrat', models.CharField(blank=True, max_length=100, null=True)),
                ('intitul', models.CharField(blank=True, max_length=255, null=True)),
                ('nationalite', models.CharField(blank=True, max_length=100, null=True)),
                ('nature', models.CharField(blank=True, choices=[('DAO', 'DAO'), ('passation', 'Passation')], max_length=100, null=True)),
                ('typee', models.CharField(blank=True, max_length=100, null=True)),
                ('type_du_contrat', models.CharField(blank=True, choices=[('fourniture', 'Fourniture'), ('travaux', 'Travaux'), ('services', 'Services'), ('etude_et_conseil', 'Étude et service de conseil'), ('prestation', 'Prestation')], max_length=100, null=True)),
                ('filiale', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_du_contrat', models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=100, null=True, unique=True)),
                ('la_monnai', models.CharField(blank=True, max_length=50, null=True)),
                ('la_taxe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montant_contrat_devise', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('montant_contrat_da', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('recours', models.CharField(blank=True, max_length=255, null=True)),
                ('id_contractant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.juridiquefournisseur')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.unite')),
            ],
        ),
    ]
