# Generated by Django 5.1.7 on 2025-03-17 05:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('contracts', '0002_remove_evaluationcontrat_id_fournisseur_and_more'),
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='unite',
            name='users',
        ),
        migrations.RenameField(
            model_name='contrat',
            old_name='reference',
            new_name='delais_estimatif_execut_livrai',
        ),
        migrations.AddField(
            model_name='contrat',
            name='copie_du_contrat',
            field=models.FileField(blank=True, null=True, upload_to='contrats/copies/'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='date_exp_du_contrat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='date_install_equip',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='date_prev_attrib_contrat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='date_prev_notif_attribu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='date_prev_signat_contrat_bon',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='date_prev_signature_contrat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='date_reel_notif_attrib',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='date_reel_sign_cont',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='date_reel_signat_contr_bon',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='date_saisie_contract',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrat',
            name='delais_execution_livraison',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='dossier_consultation',
            field=models.FileField(blank=True, null=True, upload_to='contrats/dossiers/'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='duree_attrib_contrat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='duree_contrat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='filiale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='id_contractant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.juridiquefournisseur'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='intitul',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='la_monnai',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='la_taxe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='lettre_de_prolongation',
            field=models.FileField(blank=True, null=True, upload_to='contrats/prolongations/'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='lettre_invitation',
            field=models.FileField(blank=True, null=True, upload_to='contrats/lettres_invitation/'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='montant_contrat_da',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='montant_contrat_devise',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='nationalite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='nature',
            field=models.CharField(blank=True, choices=[('DAO', 'DAO'), ('passation', 'Passation')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='pv_attribution_prov_marche',
            field=models.FileField(blank=True, null=True, upload_to='contrats/pv_attribution/'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='pv_ouverture',
            field=models.FileField(blank=True, null=True, upload_to='contrats/pv_ouverture/'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='recours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='reference_du_contrat',
            field=models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='type_du_contrat',
            field=models.CharField(blank=True, choices=[('fourniture', 'Fourniture'), ('travaux', 'Travaux'), ('services', 'Services'), ('etude_et_conseil', 'Étude et service de conseil'), ('prestation', 'Prestation')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='typee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.unite'),
        ),
        migrations.DeleteModel(
            name='EvaluationContrat',
        ),
        migrations.DeleteModel(
            name='JuridiqueFournisseur',
        ),
        migrations.DeleteModel(
            name='Unite',
        ),
    ]
