# Generated by Django 5.1.7 on 2025-04-12 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_unite_created_by'),
        ('contracts', '0003_remove_contrat_fournisseur_remove_unite_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.unite'),
        ),
    ]
